BackBundle\Entity\Category:
    type: entity
    oneToMany:
      services:
        targetEntity: BackBundle\Entity\Services
        mappedBy: category
    table: null
    repositoryClass: BackBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
